### ISSUE TITLE
Please, create Documentation/Wiki

### ISSUE THREAD

**Issue by arnisjuraga** [copona/composer-installers#1]

**Comment by prhost** [comment]
Yes, soon I will update the readme, here is little thing that you need to know. The rest will be more in the copona / copona: dev, in a while I'll upload an alpha version

**Comment by prhost** [comment]
I put the documentation in the README. In the future we can send a pull request to the composer/installers for them to add as default in the composer. So you no longer need this repository. Just do not send now because Copona is not yet famous hehe.
